-- FitFuel schema for a NEW Supabase project. Run once in Dashboard > SQL Editor.
-- The NestJS server uses SUPABASE_SECRET_KEY. No browser or anon role receives table access.
begin;

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  name varchar,
  email varchar not null unique,
  "phoneNumber" varchar,
  age bigint,
  goal varchar,
  password varchar not null,
  gender text,
  height varchar,
  weight varchar,
  bloodpressure varchar,
  heartrate varchar,
  bloodsugar varchar,
  medicalconditions text[],
  medications text[],
  dietaryrestrictions text[],
  allergies text[],
  dietarypreferences text[],
  dateofbirth date,
  "weightHistory" jsonb not null default '[]'::jsonb
);

create table if not exists public."Diet" (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  diet text,
  "generatedBy" uuid references public.users(id),
  days bigint,
  name varchar
);

create table if not exists public."User Specifications" (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  height varchar,
  weight varchar,
  goal varchar,
  gender varchar,
  "activityLevel" varchar,
  diet uuid references public."Diet"(id) on delete cascade,
  age text,
  diseases text[],
  "otherDisease" text
);

create table if not exists public.progress (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  userspecificationid uuid references public."User Specifications"(id) on delete cascade
);

create table if not exists public.refresh_tokens (
  id integer generated by default as identity primary key,
  "userId" uuid not null references public.users(id) on delete cascade,
  token text not null unique,
  "expiresAt" timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.chatroom (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  dietid uuid references public."Diet"(id) on delete set null
);

create table if not exists public.chatparticipants (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  chatroomid uuid references public.chatroom(id) on delete cascade,
  participantid uuid references public.users(id) on delete cascade
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  content text,
  senderid uuid references public.users(id) on delete set null,
  sentat timestamp,
  chatroomid uuid references public.chatroom(id) on delete cascade
);

create table if not exists public.transactions (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  dietid uuid references public."Diet"(id) on delete set null,
  ordered boolean not null default false,
  "totalAmount" text,
  subtotal double precision,
  tax double precision,
  deliveryfee double precision,
  orderstatus text,
  paymentmethod text,
  paymentdate date
);

create table if not exists public."deliveryDetails" (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  firstname varchar,
  lastname varchar,
  address varchar,
  city varchar,
  state varchar,
  zipcode varchar,
  phonenumber varchar,
  email varchar,
  startdate date
);

create table if not exists public.cart (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  diet jsonb,
  "deliveryId" uuid references public."deliveryDetails"(id),
  startdate date,
  "transactionId" uuid references public.transactions(id),
  status text not null default 'Processing',
  "endDate" date
);

create index if not exists diet_generated_by_idx on public."Diet" ("generatedBy");
create index if not exists user_specifications_diet_idx on public."User Specifications" (diet);
create index if not exists refresh_tokens_user_id_idx on public.refresh_tokens ("userId");
create index if not exists transactions_dietid_idx on public.transactions (dietid);
create index if not exists cart_transaction_id_idx on public.cart ("transactionId");

-- The application implements authentication in NestJS, not Supabase Auth.
-- Its server-only secret key accesses these tables; public API keys cannot.
alter table public.users enable row level security;
alter table public."Diet" enable row level security;
alter table public."User Specifications" enable row level security;
alter table public.progress enable row level security;
alter table public.refresh_tokens enable row level security;
alter table public.chatroom enable row level security;
alter table public.chatparticipants enable row level security;
alter table public.messages enable row level security;
alter table public.transactions enable row level security;
alter table public."deliveryDetails" enable row level security;
alter table public.cart enable row level security;

revoke all on public.users, public."Diet", public."User Specifications",
  public.progress, public.refresh_tokens, public.chatroom,
  public.chatparticipants, public.messages, public.transactions,
  public."deliveryDetails", public.cart from anon, authenticated;

grant all on public.users, public."Diet", public."User Specifications",
  public.progress, public.refresh_tokens, public.chatroom,
  public.chatparticipants, public.messages, public.transactions,
  public."deliveryDetails", public.cart to service_role;
grant usage, select on sequence public.refresh_tokens_id_seq,
  public.chatparticipants_id_seq to service_role;

-- The six RPCs called by the NestJS services.
create or replace function public.diethistory(userid uuid)
returns table (id uuid, diet text, date timestamptz, status text,
  duration bigint, title text, tags text)
language sql stable set search_path = '' as $$
  select d.id, d.diet, d.created_at, coalesce(latest_cart.status, 'Processing'),
    d.days, d.name::text, ''::text
  from public."Diet" d
  left join lateral (
    select c.status
    from public.transactions t
    join public.cart c on c."transactionId" = t.id
    where t.dietid = d.id
    order by c.created_at desc limit 1
  ) latest_cart on true
  where d."generatedBy" = userid
  order by d.created_at desc;
$$;

create or replace function public.nutritionbreakdown(userid uuid)
returns table (diet jsonb, date date)
language sql stable set search_path = '' as $$
  select c.diet, c.startdate
  from public.cart c
  join public.transactions t on t.id = c."transactionId"
  join public."Diet" d on d.id = t.dietid
  where d."generatedBy" = userid
  order by c.startdate desc;
$$;

create or replace function public.diethistorytabledata(userid uuid)
returns table (orderid uuid, ordername text, diet jsonb, status text,
  transactionid uuid, startdate date, month text, orders bigint)
language sql stable set search_path = '' as $$
  select c.id, d.name::text, coalesce(c.diet, '[]'::jsonb), c.status,
    t.id, c.startdate, to_char(c.created_at, 'Mon'), 1::bigint
  from public.cart c
  join public.transactions t on t.id = c."transactionId"
  join public."Diet" d on d.id = t.dietid
  where d."generatedBy" = userid
  order by c.created_at desc;
$$;

create or replace function public.upcomingdeliveries(userid uuid)
returns table (id uuid, diet jsonb, startdate date, enddate date, status text)
language sql stable set search_path = '' as $$
  select c.id, c.diet, c.startdate, c."endDate", c.status
  from public.cart c
  join public.transactions t on t.id = c."transactionId"
  join public."Diet" d on d.id = t.dietid
  where d."generatedBy" = userid and c."endDate" >= current_date
  order by c.startdate;
$$;

create or replace function public.paymenthistory(userid uuid)
returns table (paymentid uuid, amount text, paymentmethod text, status text,
  date date, month text, monthtotal numeric)
language sql stable set search_path = '' as $$
  select t.id, t."totalAmount", t.paymentmethod,
    coalesce(t.orderstatus, 'Processing'),
    coalesce(t.paymentdate, t.created_at::date),
    to_char(t.created_at, 'Mon'),
    sum(coalesce(nullif(t."totalAmount", '')::numeric, 0))
      over (partition by date_trunc('month', t.created_at))
  from public.transactions t
  join public."Diet" d on d.id = t.dietid
  where d."generatedBy" = userid
  order by t.created_at desc;
$$;

create or replace function public.weighthistory(userid uuid)
returns table (weight text)
language sql stable set search_path = '' as $$
  select coalesce(u."weightHistory", '[]'::jsonb)::text
  from public.users u where u.id = userid;
$$;

create or replace function public.updateprofile(
  userid uuid, name text, email text, "phoneNumber" text, age bigint,
  goal text, gender text, height text, weight text, bloodpressure text,
  heartrate text, bloodsugar text, medicalconditions text[], medications text[],
  dietaryrestrictions text[], allergies text[], dietarypreferences text[],
  dateofbirth date
)
returns jsonb language sql set search_path = '' as $$
  update public.users u set
    name = $2, email = $3, "phoneNumber" = $4, age = $5,
    goal = $6, gender = $7, height = $8, weight = $9,
    bloodpressure = $10, heartrate = $11, bloodsugar = $12,
    medicalconditions = $13, medications = $14,
    dietaryrestrictions = $15, allergies = $16,
    dietarypreferences = $17, dateofbirth = $18
  where u.id = $1
  returning to_jsonb(u) - 'password';
$$;

revoke all on function public.diethistory(uuid), public.nutritionbreakdown(uuid),
  public.diethistorytabledata(uuid), public.upcomingdeliveries(uuid),
  public.paymenthistory(uuid), public.weighthistory(uuid) from public, anon, authenticated;
grant execute on function public.diethistory(uuid), public.nutritionbreakdown(uuid),
  public.diethistorytabledata(uuid), public.upcomingdeliveries(uuid),
  public.paymenthistory(uuid), public.weighthistory(uuid) to service_role;

revoke all on function public.updateprofile(uuid, text, text, text, bigint,
  text, text, text, text, text, text, text, text[], text[], text[], text[],
  text[], date) from public, anon, authenticated;
grant execute on function public.updateprofile(uuid, text, text, text, bigint,
  text, text, text, text, text, text, text, text[], text[], text[], text[],
  text[], date) to service_role;

commit;
